//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vsempoka2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ед изм.
    /// </summary>
    // *** Start programmer edit section *** (ЕдИзм CustomAttributes)

    // *** End programmer edit section *** (ЕдИзм CustomAttributes)
    public enum ЕдИзм
    {
        
        /// <summary>
        /// шт.
        /// </summary>
        // *** Start programmer edit section *** (ЕдИзм.шт CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.шт CustomAttributes)
        [Caption("шт")]
        шт,
        
        /// <summary>
        /// кг.
        /// </summary>
        // *** Start programmer edit section *** (ЕдИзм.кг CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.кг CustomAttributes)
        [Caption("шт")]
        кг,
        
        /// <summary>
        /// тонн.
        /// </summary>
        // *** Start programmer edit section *** (ЕдИзм.тонн CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.тонн CustomAttributes)
        [Caption("тонн")]
        тонн,
        
        /// <summary>
        /// литр.
        /// </summary>
        // *** Start programmer edit section *** (ЕдИзм.литр CustomAttributes)

        // *** End programmer edit section *** (ЕдИзм.литр CustomAttributes)
        [Caption("литр")]
        литр,
    }
}
