//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vsempoka2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиенты.
    /// </summary>
    // *** Start programmer edit section *** (Клиенты CustomAttributes)

    // *** End programmer edit section *** (Клиенты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентыE", new string[] {
            "НаимЗаказа as \'Наим заказа\'",
            "ИНН as \'ИНН\'",
            "Телефон as \'Телефон\'",
            "ПунктПостав as \'Пункт постав\'",
            "РасСчет as \'Рас счет\'"})]
    [View("КлиентыL", new string[] {
            "НаимЗаказа as \'Наим заказа\'",
            "ИНН as \'ИНН\'",
            "Телефон as \'Телефон\'",
            "ПунктПостав as \'Пункт постав\'",
            "РасСчет as \'Рас счет\'"})]
    public class Клиенты : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаимЗаказа;
        
        private int fИНН;
        
        private int fТелефон;
        
        private string fПунктПостав;
        
        private int fРасСчет;
        
        // *** Start programmer edit section *** (Клиенты CustomMembers)

        // *** End programmer edit section *** (Клиенты CustomMembers)

        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ИНН CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ИНН Get start)

                // *** End programmer edit section *** (Клиенты.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (Клиенты.ИНН Get end)

                // *** End programmer edit section *** (Клиенты.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ИНН Set start)

                // *** End programmer edit section *** (Клиенты.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (Клиенты.ИНН Set end)

                // *** End programmer edit section *** (Клиенты.ИНН Set end)
            }
        }
        
        /// <summary>
        /// НаимЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.НаимЗаказа CustomAttributes)

        // *** End programmer edit section *** (Клиенты.НаимЗаказа CustomAttributes)
        [StrLen(255)]
        public virtual string НаимЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.НаимЗаказа Get start)

                // *** End programmer edit section *** (Клиенты.НаимЗаказа Get start)
                string result = this.fНаимЗаказа;
                // *** Start programmer edit section *** (Клиенты.НаимЗаказа Get end)

                // *** End programmer edit section *** (Клиенты.НаимЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.НаимЗаказа Set start)

                // *** End programmer edit section *** (Клиенты.НаимЗаказа Set start)
                this.fНаимЗаказа = value;
                // *** Start programmer edit section *** (Клиенты.НаимЗаказа Set end)

                // *** End programmer edit section *** (Клиенты.НаимЗаказа Set end)
            }
        }
        
        /// <summary>
        /// ПунктПостав.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ПунктПостав CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ПунктПостав CustomAttributes)
        [StrLen(255)]
        public virtual string ПунктПостав
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ПунктПостав Get start)

                // *** End programmer edit section *** (Клиенты.ПунктПостав Get start)
                string result = this.fПунктПостав;
                // *** Start programmer edit section *** (Клиенты.ПунктПостав Get end)

                // *** End programmer edit section *** (Клиенты.ПунктПостав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ПунктПостав Set start)

                // *** End programmer edit section *** (Клиенты.ПунктПостав Set start)
                this.fПунктПостав = value;
                // *** Start programmer edit section *** (Клиенты.ПунктПостав Set end)

                // *** End programmer edit section *** (Клиенты.ПунктПостав Set end)
            }
        }
        
        /// <summary>
        /// РасСчет.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.РасСчет CustomAttributes)

        // *** End programmer edit section *** (Клиенты.РасСчет CustomAttributes)
        public virtual int РасСчет
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.РасСчет Get start)

                // *** End programmer edit section *** (Клиенты.РасСчет Get start)
                int result = this.fРасСчет;
                // *** Start programmer edit section *** (Клиенты.РасСчет Get end)

                // *** End programmer edit section *** (Клиенты.РасСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.РасСчет Set start)

                // *** End programmer edit section *** (Клиенты.РасСчет Set start)
                this.fРасСчет = value;
                // *** Start programmer edit section *** (Клиенты.РасСчет Set end)

                // *** End programmer edit section *** (Клиенты.РасСчет Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.Телефон CustomAttributes)

        // *** End programmer edit section *** (Клиенты.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.Телефон Get start)

                // *** End programmer edit section *** (Клиенты.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (Клиенты.Телефон Get end)

                // *** End programmer edit section *** (Клиенты.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.Телефон Set start)

                // *** End programmer edit section *** (Клиенты.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (Клиенты.Телефон Set end)

                // *** End programmer edit section *** (Клиенты.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыE", typeof(IIS.Vsempoka2.Клиенты));
                }
            }
            
            /// <summary>
            /// "КлиентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыL", typeof(IIS.Vsempoka2.Клиенты));
                }
            }
        }
    }
}
