//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vsempoka2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Пункт погруз.
    /// </summary>
    // *** Start programmer edit section *** (ПунктПогруз CustomAttributes)

    // *** End programmer edit section *** (ПунктПогруз CustomAttributes)
    [AutoAltered()]
    [Caption("Пункт погруз")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПунктПогрузE", new string[] {
            "Наим as \'Наим\'",
            "Адрес as \'Адрес\'"})]
    [View("ПунктПогрузL", new string[] {
            "Наим as \'Наим\'",
            "Адрес as \'Адрес\'"})]
    public class ПунктПогруз : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаим;
        
        private string fАдрес;
        
        // *** Start programmer edit section *** (ПунктПогруз CustomMembers)

        // *** End programmer edit section *** (ПунктПогруз CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (ПунктПогруз.Адрес CustomAttributes)

        // *** End programmer edit section *** (ПунктПогруз.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (ПунктПогруз.Адрес Get start)

                // *** End programmer edit section *** (ПунктПогруз.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (ПунктПогруз.Адрес Get end)

                // *** End programmer edit section *** (ПунктПогруз.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПунктПогруз.Адрес Set start)

                // *** End programmer edit section *** (ПунктПогруз.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (ПунктПогруз.Адрес Set end)

                // *** End programmer edit section *** (ПунктПогруз.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Наим.
        /// </summary>
        // *** Start programmer edit section *** (ПунктПогруз.Наим CustomAttributes)

        // *** End programmer edit section *** (ПунктПогруз.Наим CustomAttributes)
        [StrLen(255)]
        public virtual string Наим
        {
            get
            {
                // *** Start programmer edit section *** (ПунктПогруз.Наим Get start)

                // *** End programmer edit section *** (ПунктПогруз.Наим Get start)
                string result = this.fНаим;
                // *** Start programmer edit section *** (ПунктПогруз.Наим Get end)

                // *** End programmer edit section *** (ПунктПогруз.Наим Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПунктПогруз.Наим Set start)

                // *** End programmer edit section *** (ПунктПогруз.Наим Set start)
                this.fНаим = value;
                // *** Start programmer edit section *** (ПунктПогруз.Наим Set end)

                // *** End programmer edit section *** (ПунктПогруз.Наим Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПунктПогрузE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПунктПогрузE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПунктПогрузE", typeof(IIS.Vsempoka2.ПунктПогруз));
                }
            }
            
            /// <summary>
            /// "ПунктПогрузL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПунктПогрузL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПунктПогрузL", typeof(IIS.Vsempoka2.ПунктПогруз));
                }
            }
        }
    }
}
