//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vsempoka2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус заказа.
    /// </summary>
    // *** Start programmer edit section *** (СтатусЗаказа CustomAttributes)

    // *** End programmer edit section *** (СтатусЗаказа CustomAttributes)
    public enum СтатусЗаказа
    {
        
        /// <summary>
        /// ВОбработке.
        /// </summary>
        // *** Start programmer edit section *** (СтатусЗаказа.ВОбработке CustomAttributes)

        // *** End programmer edit section *** (СтатусЗаказа.ВОбработке CustomAttributes)
        [Caption("ВОбработке")]
        ВОбработке,
        
        /// <summary>
        /// Доставлен.
        /// </summary>
        // *** Start programmer edit section *** (СтатусЗаказа.Доставлен CustomAttributes)

        // *** End programmer edit section *** (СтатусЗаказа.Доставлен CustomAttributes)
        [Caption("Доставлен")]
        Доставлен,
        
        /// <summary>
        /// НеДоставлен.
        /// </summary>
        // *** Start programmer edit section *** (СтатусЗаказа.НеДоставлен CustomAttributes)

        // *** End programmer edit section *** (СтатусЗаказа.НеДоставлен CustomAttributes)
        [Caption("НеДоставлен")]
        НеДоставлен,
        
        /// <summary>
        /// Отменен.
        /// </summary>
        // *** Start programmer edit section *** (СтатусЗаказа.Отменен CustomAttributes)

        // *** End programmer edit section *** (СтатусЗаказа.Отменен CustomAttributes)
        [Caption("Отменен")]
        Отменен,
    }
}
