//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vsempoka2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Форм рез пост.
    /// </summary>
    // *** Start programmer edit section *** (ФормРезПост CustomAttributes)

    // *** End programmer edit section *** (ФормРезПост CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормРезПостE", new string[] {
            "Дата as \'Дата\'",
            "СтатусЗаказа as \'Статус заказа\'",
            "НаличиеДеф as \'Наличие деф\'",
            "УдовлКл as \'Удовл кл\'",
            "ФормирРаспред as \'Формир распред\'",
            "ФормирРаспред.НомерРаспред as \'Номер распред\'"}, Hidden=new string[] {
            "ФормирРаспред.НомерРаспред"})]
    [MasterViewDefineAttribute("ФормРезПостE", "ФормирРаспред", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерРаспред")]
    [View("ФормРезПостL", new string[] {
            "Дата as \'Дата\'",
            "СтатусЗаказа as \'Статус заказа\'",
            "НаличиеДеф as \'Наличие деф\'",
            "УдовлКл as \'Удовл кл\'",
            "ФормирРаспред.НомерРаспред as \'Номер распред\'"})]
    public class ФормРезПост : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Vsempoka2.СтатусЗаказа fСтатусЗаказа;
        
        private bool fНаличиеДеф;
        
        private IIS.Vsempoka2.УдовлКл fУдовлКл;
        
        private IIS.Vsempoka2.ФормирРаспред fФормирРаспред;
        
        // *** Start programmer edit section *** (ФормРезПост CustomMembers)

        // *** End programmer edit section *** (ФормРезПост CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормРезПост.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормРезПост.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормРезПост.Дата Get start)

                // *** End programmer edit section *** (ФормРезПост.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормРезПост.Дата Get end)

                // *** End programmer edit section *** (ФормРезПост.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормРезПост.Дата Set start)

                // *** End programmer edit section *** (ФормРезПост.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормРезПост.Дата Set end)

                // *** End programmer edit section *** (ФормРезПост.Дата Set end)
            }
        }
        
        /// <summary>
        /// НаличиеДеф.
        /// </summary>
        // *** Start programmer edit section *** (ФормРезПост.НаличиеДеф CustomAttributes)

        // *** End programmer edit section *** (ФормРезПост.НаличиеДеф CustomAttributes)
        public virtual bool НаличиеДеф
        {
            get
            {
                // *** Start programmer edit section *** (ФормРезПост.НаличиеДеф Get start)

                // *** End programmer edit section *** (ФормРезПост.НаличиеДеф Get start)
                bool result = this.fНаличиеДеф;
                // *** Start programmer edit section *** (ФормРезПост.НаличиеДеф Get end)

                // *** End programmer edit section *** (ФормРезПост.НаличиеДеф Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормРезПост.НаличиеДеф Set start)

                // *** End programmer edit section *** (ФормРезПост.НаличиеДеф Set start)
                this.fНаличиеДеф = value;
                // *** Start programmer edit section *** (ФормРезПост.НаличиеДеф Set end)

                // *** End programmer edit section *** (ФормРезПост.НаличиеДеф Set end)
            }
        }
        
        /// <summary>
        /// СтатусЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (ФормРезПост.СтатусЗаказа CustomAttributes)

        // *** End programmer edit section *** (ФормРезПост.СтатусЗаказа CustomAttributes)
        public virtual IIS.Vsempoka2.СтатусЗаказа СтатусЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (ФормРезПост.СтатусЗаказа Get start)

                // *** End programmer edit section *** (ФормРезПост.СтатусЗаказа Get start)
                IIS.Vsempoka2.СтатусЗаказа result = this.fСтатусЗаказа;
                // *** Start programmer edit section *** (ФормРезПост.СтатусЗаказа Get end)

                // *** End programmer edit section *** (ФормРезПост.СтатусЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормРезПост.СтатусЗаказа Set start)

                // *** End programmer edit section *** (ФормРезПост.СтатусЗаказа Set start)
                this.fСтатусЗаказа = value;
                // *** Start programmer edit section *** (ФормРезПост.СтатусЗаказа Set end)

                // *** End programmer edit section *** (ФормРезПост.СтатусЗаказа Set end)
            }
        }
        
        /// <summary>
        /// УдовлКл.
        /// </summary>
        // *** Start programmer edit section *** (ФормРезПост.УдовлКл CustomAttributes)

        // *** End programmer edit section *** (ФормРезПост.УдовлКл CustomAttributes)
        public virtual IIS.Vsempoka2.УдовлКл УдовлКл
        {
            get
            {
                // *** Start programmer edit section *** (ФормРезПост.УдовлКл Get start)

                // *** End programmer edit section *** (ФормРезПост.УдовлКл Get start)
                IIS.Vsempoka2.УдовлКл result = this.fУдовлКл;
                // *** Start programmer edit section *** (ФормРезПост.УдовлКл Get end)

                // *** End programmer edit section *** (ФормРезПост.УдовлКл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормРезПост.УдовлКл Set start)

                // *** End programmer edit section *** (ФормРезПост.УдовлКл Set start)
                this.fУдовлКл = value;
                // *** Start programmer edit section *** (ФормРезПост.УдовлКл Set end)

                // *** End programmer edit section *** (ФормРезПост.УдовлКл Set end)
            }
        }
        
        /// <summary>
        /// Форм рез пост.
        /// </summary>
        // *** Start programmer edit section *** (ФормРезПост.ФормирРаспред CustomAttributes)

        // *** End programmer edit section *** (ФормРезПост.ФормирРаспред CustomAttributes)
        [PropertyStorage(new string[] {
                "ФормирРаспред"})]
        [NotNull()]
        public virtual IIS.Vsempoka2.ФормирРаспред ФормирРаспред
        {
            get
            {
                // *** Start programmer edit section *** (ФормРезПост.ФормирРаспред Get start)

                // *** End programmer edit section *** (ФормРезПост.ФормирРаспред Get start)
                IIS.Vsempoka2.ФормирРаспред result = this.fФормирРаспред;
                // *** Start programmer edit section *** (ФормРезПост.ФормирРаспред Get end)

                // *** End programmer edit section *** (ФормРезПост.ФормирРаспред Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормРезПост.ФормирРаспред Set start)

                // *** End programmer edit section *** (ФормРезПост.ФормирРаспред Set start)
                this.fФормирРаспред = value;
                // *** Start programmer edit section *** (ФормРезПост.ФормирРаспред Set end)

                // *** End programmer edit section *** (ФормРезПост.ФормирРаспред Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормРезПостE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормРезПостE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормРезПостE", typeof(IIS.Vsempoka2.ФормРезПост));
                }
            }
            
            /// <summary>
            /// "ФормРезПостL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормРезПостL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормРезПостL", typeof(IIS.Vsempoka2.ФормРезПост));
                }
            }
        }
    }
}
